name: $(SemVer)

variables:
  BuildRev: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  SemVer: $[ variables['Build.SourceBranchName'] ]
  CommitId: $(Build.SourceVersion)

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

resources:
  containers:
  - container: couchdb
    image: couchdb:2.3.1
    ports:
    - 5984:5984
    env:
      COUCHDB_USER: $(MyCouch_User)
      COUCHDB_PASSWORD: $(MyCouch_Pass)

pool:
  vmImage: ubuntu-18.04

stages:
- template: azure-templates/stage-build.yml
- template: azure-templates/stage-deploy.yml