stages:
- stage: Build
  jobs:
  - job: BuildTestPack
    displayName: 'Build, test & pack'
    timeoutInMinutes: 5
    cancelTimeoutInMinutes: 2
    services:
      couchdb: couchdb
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: build
        projects: 'source/*.sln'
        arguments: '-c $(BuildConfiguration) --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=$(SemVer) -p:InformationalVersion=$(CommitId)'

    - task: DotNetCoreCLI@2
      displayName: 'UnitTests'
      inputs:
        command: test
        projects: 'source/tests/**/UnitTests.csproj'
        arguments: '-c $(BuildConfiguration) --no-build'
        testRunTitle: 'UnitTests'

    - task: DotNetCoreCLI@2
      displayName: 'IntegrationTests'
      inputs:
        command: test
        projects: 'source/tests/**/IntegrationTests.csproj'
        arguments: '-c $(BuildConfiguration) --no-build'
        testRunTitle: 'IntegrationTests'
  
    - task: DotNetCoreCLI@2
      displayName: 'Pack Nupkg'
      inputs:
        command: custom
        custom: pack
        projects: 'source/*.sln'
        arguments: '-c $(BuildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory) -p:Version=$(SemVer) -p:InformationalVersion=$(CommitId)'
  
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: Artifacts